name: 最新Windows

on:
  workflow_dispatch:
    inputs:
      authcode:
        description: "CRD代码"
        required: true
      pincode:
        description: "6位PIN码"
        required: true

jobs:
  setup:
    runs-on: windows-latest
    steps:
      - 使用: actions/checkout@v3
      - 名称: 初始化设置
        运行: ./setup/win-latest/setup.ps1
      - 名称: 启动Chrome远程桌面(CRD)
        运行: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
      - 名称: 保持活动
        运行: ./setup/win-latest/timeout.ps1